### ISSUE TITLE
Validate user name to avoid null values

### ISSUE THREAD

**Issue by PriBaez** [lopezbec/AI_Gamification_Python#72]
A potential bug caused by username input has been detected. If this entry is empty/null this causes the program to crash every time you try to open the leaderboard later.

**Here the error output:**

```
Traceback (most recent call last):
    window = MainWindow()
             ^^^^^^^^^^^^
  File "C:\Users\Admin\VSCode\AI_Gamification_Python\Elmer\Daniel_JSON_Files_Elmer\Codigos_LeaderBoard\Main_Leaderboard_FV.py", line 41, in __init__
    self.populate_leaderboard_table()
  File "C:\Users\Admin\VSCode\AI_Gamification_Python\Elmer\Daniel_JSON_Files_Elmer\Codigos_LeaderBoard\Main_Leaderboard_FV.py", line 287, in populate_leaderboard_table

    ordered_users = self.order_leaderboard(filtered_users)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\VSCode\AI_Gamification_Python\Elmer\Daniel_JSON_Files_Elmer\Codigos_LeaderBoard\Main_Leaderboard_FV.py", line 317, in order_leaderboard
    return sorted(users, key=lambda x: x['name'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by Elmerluis0129** [comment]
Fixed!
